### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-buchihin#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
2) Відомо, що Git-система контроля версій використовує поняття “гілка” (branch). 
Поясніть, будь ласка, як використання такої “гілки” 
може підвищити безпеку процесів створення програмного продукту?

**Comment by Arhemius** [comment]
Можна ізолювати створення певних аспектів програм так, щоб зміни коду не впливали на її стабільну версію, допоки це не дозволять, поєднавши гілки.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
